name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Test
      run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Generate coverage percentage
      id: coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.txt | grep total | grep -Eo '[0-9]+\.[0-9]+')
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Total coverage: $COVERAGE%"

    - name: Create coverage.json file
      if: github.ref == 'refs/heads/main'
      run: |
        echo "{\"schemaVersion\":1,\"label\":\"coverage\",\"message\":\"${{ steps.coverage.outputs.percentage }}%\",\"color\":\"$([ $(echo "${{ steps.coverage.outputs.percentage }} >= 80" | bc -l) -eq 1 ] && echo 'green' || [ $(echo "${{ steps.coverage.outputs.percentage }} >= 60" | bc -l) -eq 1 ] && echo 'yellow' || echo 'red')\"}" > coverage.json
        cat coverage.json

    - name: Update Gist with coverage data
      uses: exuanbo/actions-deploy-gist@v1
      if: github.ref == 'refs/heads/main'
      with:
        token: ${{ secrets.GIST_SECRET }}
        gist_id: ${{ secrets.GIST_ID }}
        file_path: coverage.json
        file_type: json 