name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Test
      run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Generate coverage percentage
      id: coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.txt | grep total | grep -Eo '[0-9]+\.[0-9]+')
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Total coverage: $COVERAGE%"

    - name: Generate coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      if: github.ref == 'refs/heads/main'
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: coverage.json
        label: coverage
        message: ${{ steps.coverage.outputs.percentage }}%
        color: ${{ steps.coverage.outputs.percentage >= 80 && 'green' || steps.coverage.outputs.percentage >= 60 && 'yellow' || 'red' }}
        style: flat 